/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.io.InputStream;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Imah Idris
 */
public class laporan extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
   // String vmd5;

    /**
     * Creates new form menuAdmin
     */
    public laporan() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogKeamanan = new javax.swing.JDialog();
        dcDarikea = new com.toedter.calendar.JDateChooser();
        dcSampaikea = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cetakkea = new javax.swing.JButton();
        jDialogKebersihan = new javax.swing.JDialog();
        dcDarikeb = new com.toedter.calendar.JDateChooser();
        dcSampaikeb = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cetakkeb = new javax.swing.JButton();
        jDialogPembayaran = new javax.swing.JDialog();
        dcDarib = new com.toedter.calendar.JDateChooser();
        dcSampaib = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bayarpetugas = new javax.swing.JButton();
        kebersihan = new javax.swing.JButton();
        warga = new javax.swing.JButton();
        petugas = new javax.swing.JButton();
        keamanan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        jDialogKeamanan.setMinimumSize(new java.awt.Dimension(420, 140));

        jLabel5.setText("Dari");

        jLabel6.setText("Sampai");

        cetakkea.setText("CETAK");
        cetakkea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakkeaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogKeamananLayout = new javax.swing.GroupLayout(jDialogKeamanan.getContentPane());
        jDialogKeamanan.getContentPane().setLayout(jDialogKeamananLayout);
        jDialogKeamananLayout.setHorizontalGroup(
            jDialogKeamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKeamananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogKeamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDarikea, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jDialogKeamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcSampaikea, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
            .addGroup(jDialogKeamananLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(cetakkea, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogKeamananLayout.setVerticalGroup(
            jDialogKeamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKeamananLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogKeamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogKeamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcSampaikea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDarikea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cetakkea)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDialogKebersihan.setMinimumSize(new java.awt.Dimension(420, 140));

        jLabel7.setText("Dari");

        jLabel8.setText("Sampai");

        cetakkeb.setText("CETAK");
        cetakkeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakkebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogKebersihanLayout = new javax.swing.GroupLayout(jDialogKebersihan.getContentPane());
        jDialogKebersihan.getContentPane().setLayout(jDialogKebersihanLayout);
        jDialogKebersihanLayout.setHorizontalGroup(
            jDialogKebersihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKebersihanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogKebersihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDarikeb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jDialogKebersihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcSampaikeb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
            .addGroup(jDialogKebersihanLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(cetakkeb, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogKebersihanLayout.setVerticalGroup(
            jDialogKebersihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKebersihanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogKebersihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogKebersihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcSampaikeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDarikeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cetakkeb)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDialogPembayaran.setMinimumSize(new java.awt.Dimension(420, 140));

        jLabel9.setText("Dari");

        jLabel10.setText("Sampai");

        jButton4.setText("CETAK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogPembayaranLayout = new javax.swing.GroupLayout(jDialogPembayaran.getContentPane());
        jDialogPembayaran.getContentPane().setLayout(jDialogPembayaranLayout);
        jDialogPembayaranLayout.setHorizontalGroup(
            jDialogPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDarib, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jDialogPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcSampaib, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
            .addGroup(jDialogPembayaranLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogPembayaranLayout.setVerticalGroup(
            jDialogPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPembayaranLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcSampaib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDarib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/LOGO 1.png"))); // NOI18N
        jLabel4.setOpaque(true);

        bayarpetugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bayarpetugas.setText("Pembayaran Petugas");
        bayarpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarpetugasActionPerformed(evt);
            }
        });

        kebersihan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kebersihan.setText("Iuran Kebersihan");
        kebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebersihanActionPerformed(evt);
            }
        });

        warga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        warga.setText("Data Warga");
        warga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wargaActionPerformed(evt);
            }
        });

        petugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        petugas.setText("Data Petugas");
        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });

        keamanan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keamanan.setText("Iuran Keamanan");
        keamanan.setAutoscrolls(true);
        keamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keamananActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dana Iuran");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sistem Pembayaran dan Pengalokasian");

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keamanan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warga, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayarpetugas))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(warga)
                        .addGap(18, 18, 18)
                        .addComponent(petugas)
                        .addGap(74, 74, 74)
                        .addComponent(kebersihan)
                        .addGap(18, 18, 18)
                        .addComponent(bayarpetugas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keamanan))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bayarpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarpetugasActionPerformed
        // TODO add your handling code here:
        jDialogPembayaran.setLocationRelativeTo(this);
        jDialogPembayaran.setVisible(true);
    }//GEN-LAST:event_bayarpetugasActionPerformed

    private void kebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebersihanActionPerformed
        // TODO add your handling code here:
        jDialogKebersihan.setLocationRelativeTo(this);
        jDialogKebersihan.setVisible(true);
    }//GEN-LAST:event_kebersihanActionPerformed

    private void wargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wargaActionPerformed
        // TODO add your handling code here:
        try {
//            HashMap hash = new HashMap();

            InputStream is = getClass().getResourceAsStream("/report/reportWarga.jrxml");
            JasperReport jasperReport = JasperCompileManager.compileReport(is);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer.viewReport(jasperPrint, false);
        }catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_wargaActionPerformed

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
        // TODO add your handling code here:
        try {
//            HashMap hash = new HashMap();

            InputStream is = getClass().getResourceAsStream("/report/reportPetugas.jrxml");
            JasperReport jasperReport = JasperCompileManager.compileReport(is);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer.viewReport(jasperPrint, false);
        }catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_petugasActionPerformed

    private void keamananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keamananActionPerformed
        // TODO add your handling code here:
        jDialogKeamanan.setLocationRelativeTo(this);
        jDialogKeamanan.setVisible(true);
    }//GEN-LAST:event_keamananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menuUtama mu = new menuUtama();
        mu.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cetakkeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakkeaActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
        String dari = date.format(dcDarikea.getDate());
        String sampai = date.format(dcSampaikea.getDate());
        try {
            HashMap hash = new HashMap();
            hash.put("dari", dari);
            hash.put("sampai", sampai);

            InputStream is = getClass().getResourceAsStream("/report/reportKeamanan.jrxml");
            JasperReport jasperReport = JasperCompileManager.compileReport(is);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, conn);
            JasperViewer.viewReport(jasperPrint, false);
            jDialogKeamanan.dispose();
        }catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_cetakkeaActionPerformed

    private void cetakkebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakkebActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
        String dari = date.format(dcDarikeb.getDate());
        String sampai = date.format(dcSampaikeb.getDate());
        try {
            HashMap hash = new HashMap();
            hash.put("dari", dari);
            hash.put("sampai", sampai);

            InputStream is = getClass().getResourceAsStream("/report/reportKebersihan.jrxml");
            JasperReport jasperReport = JasperCompileManager.compileReport(is);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, conn);
            JasperViewer.viewReport(jasperPrint, false);
            jDialogKebersihan.dispose();
        }catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_cetakkebActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
        String dari = date.format(dcDarib.getDate());
        String sampai = date.format(dcSampaib.getDate());
        try {
            HashMap hash = new HashMap();
            hash.put("dari", dari);
            hash.put("sampai", sampai);

            InputStream is = getClass().getResourceAsStream("/report/reportBayarPetugas.jrxml");
            JasperReport jasperReport = JasperCompileManager.compileReport(is);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, conn);
            JasperViewer.viewReport(jasperPrint, false);
            jDialogPembayaran.dispose();
        }catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarpetugas;
    private javax.swing.JButton cetakkea;
    private javax.swing.JButton cetakkeb;
    private com.toedter.calendar.JDateChooser dcDarib;
    private com.toedter.calendar.JDateChooser dcDarikea;
    private com.toedter.calendar.JDateChooser dcDarikeb;
    private com.toedter.calendar.JDateChooser dcSampaib;
    private com.toedter.calendar.JDateChooser dcSampaikea;
    private com.toedter.calendar.JDateChooser dcSampaikeb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialogKeamanan;
    private javax.swing.JDialog jDialogKebersihan;
    private javax.swing.JDialog jDialogPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton keamanan;
    private javax.swing.JButton kebersihan;
    private javax.swing.JButton petugas;
    private javax.swing.JButton warga;
    // End of variables declaration//GEN-END:variables
}
