/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Imah Idris
 */
public class menuUtama extends javax.swing.JFrame {
   // String vmd5;

    /**
     * Creates new form menuAdmin
     */
    public menuUtama() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        bArtis = new javax.swing.JButton();
        bKlien = new javax.swing.JButton();
        bKaryawan = new javax.swing.JButton();
        bPekerjaan = new javax.swing.JButton();
        bJadwalUlang = new javax.swing.JButton();
        bPembayaran = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/LOGO 1.png"))); // NOI18N
        jLabel4.setOpaque(true);

        bArtis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bArtis.setText("Pembayaran Petugas");
        bArtis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtisActionPerformed(evt);
            }
        });

        bKlien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bKlien.setText("Iuran Kebersihan");
        bKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKlienActionPerformed(evt);
            }
        });

        bKaryawan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bKaryawan.setText("Data Warga");
        bKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKaryawanActionPerformed(evt);
            }
        });

        bPekerjaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bPekerjaan.setText("Data Petugas");
        bPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPekerjaanActionPerformed(evt);
            }
        });

        bJadwalUlang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bJadwalUlang.setText("Iuran Keamanan");
        bJadwalUlang.setAutoscrolls(true);
        bJadwalUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJadwalUlangActionPerformed(evt);
            }
        });

        bPembayaran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bPembayaran.setText("Laporan");
        bPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPembayaranActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dana Iuran");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sistem Pembayaran dan Pengalokasian");
        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bJadwalUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bArtis)
                    .addComponent(bPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(bPekerjaan)
                        .addGap(74, 74, 74)
                        .addComponent(bKlien)
                        .addGap(18, 18, 18)
                        .addComponent(bArtis)
                        .addGap(18, 18, 18)
                        .addComponent(bPembayaran))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bJadwalUlang))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bArtisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtisActionPerformed
        // TODO add your handling code here:
        bayarpetugas tl = new bayarpetugas();
        tl.show();
        this.dispose();
    }//GEN-LAST:event_bArtisActionPerformed

    private void bKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKlienActionPerformed
        // TODO add your handling code here:
        kebersihan cl = new kebersihan();
        cl.show();
        this.dispose();
    }//GEN-LAST:event_bKlienActionPerformed

    private void bKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKaryawanActionPerformed
        // TODO add your handling code here:
        warga us = new warga();
        us.show();
        this.dispose();
    }//GEN-LAST:event_bKaryawanActionPerformed

    private void bPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPekerjaanActionPerformed
        // TODO add your handling code here:
        petugas nj = new petugas();
        nj.show();
    }//GEN-LAST:event_bPekerjaanActionPerformed

    private void bJadwalUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJadwalUlangActionPerformed
        // TODO add your handling code here:
        keamanan rs = new keamanan();
        rs.show();
    }//GEN-LAST:event_bJadwalUlangActionPerformed

    private void bPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPembayaranActionPerformed
        // TODO add your handling code here:
        laporan pm = new laporan();
        pm.show();
        this.dispose();
    }//GEN-LAST:event_bPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bArtis;
    private javax.swing.JButton bJadwalUlang;
    private javax.swing.JButton bKaryawan;
    private javax.swing.JButton bKlien;
    private javax.swing.JButton bPekerjaan;
    private javax.swing.JButton bPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
